const htmlTeachers = [
  {
    id: "carloe",
    name: "Carole Towne",
    designation: "Economics teacher",
    intro:
      "Ready to unravel the complexities of supply, demand, and market forces? Dive into my Economics course now!",
    lessons: 132,
    courses: 24,
    students: 250,
    price: 32,
    oldPrice: 46,
    rating: 4.9,
    label: "TOP Tutor",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    sale: true,
  },
  {
    id: "carloe1",
    name: "Ralph Legros",
    designation: "Economics teacher",
    intro:
      "From micro to macroeconomics, discover the keys to understanding economic phenomena in my comprehensive courses.",
    lessons: 174,
    courses: 32,
    students: 250,
    price: 23,
    oldPrice: 32,
    rating: 4.9,
    label: "Certified",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    sale: true,
  },
  {
    id: "carloe2",
    name: "Jenny Wilson",
    designation: "Economics teacher",
    intro:
      "Economics isn't just a subject - it's the lens through which we view society. I will help you explore its profound implications.",
    lessons: 116,
    courses: 17,
    students: 150,
    price: 17,
    rating: 4.9,
    label: "TOP Tutor",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    sale: false,
  },
  {
    id: "carloe3",
    name: "Jenny Wilson 2",
    designation: "Economics teacher",
    intro:
      "Economics isn't just a subject - it's the lens through which we view society. I will help you explore its profound implications.",
    lessons: 116,
    courses: 17,
    students: 150,
    price: 17,
    rating: 4.9,
    label: "TOP Tutor",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    sale: false,
  },
  {
    id: "carloe4",
    name: "Jenny Wilson 3",
    designation: "Economics teacher",
    intro:
      "Economics isn't just a subject - it's the lens through which we view society. I will help you explore its profound implications.",
    lessons: 116,
    courses: 17,
    students: 150,
    price: 17,
    rating: 4.9,
    label: "TOP Tutor",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    sale: false,
  },
];

export default htmlTeachers;
