export const TrackTopics = [
  { "id": 1, "title": "Introduction to Go", "order": 1, "is_completed": true },
  { "id": 2, "title": "Code organization. Design principles", "order": 2, "is_completed": true },
  { "id": 3, "title": "Files", "order": 3, "is_completed": true },
  { "id": 4, "title": "Comments", "order": 4, "is_completed": true },
  { "id": 5, "title": "Variables and constants", "order": 5, "is_completed": true },
  { "id": 6, "title": "Input/Output", "order": 6, "is_completed": false },
  { "id": 7, "title": "Pointers", "order": 7, "is_completed": false },
  { "id": 8, "title": "Control statements", "order": 8, "is_completed": false },
  { "id": 9, "title": "Loops", "order": 9, "is_completed": false },
  { "id": 10, "title": "Packages", "order": 10, "is_completed": false },
  { "id": 11, "title": "Primitive types", "order": 11, "is_completed": false },
  { "id": 12, "title": "Arrays", "order": 12, "is_completed": false },
  { "id": 13, "title": "Slices", "order": 13, "is_completed": false },
  { "id": 14, "title": "Working with slices", "order": 14, "is_completed": false },
  { "id": 15, "title": "Strings", "order": 15, "is_completed": false },
  { "id": 16, "title": "String formatting", "order": 16, "is_completed": false },
  { "id": 17, "title": "Structs", "order": 17, "is_completed": false },
  { "id": 18, "title": "Type conversion and overflow", "order": 18, "is_completed": false },
  { "id": 19, "title": "Slice expressions", "order": 19, "is_completed": false },
  { "id": 20, "title": "Introduction to logging", "order": 20, "is_completed": false },
  { "id": 21, "title": "Errors", "order": 21, "is_completed": false },
  { "id": 22, "title": "Single Responsibility Principle", "order": 22, "is_completed": false },
  { "id": 23, "title": "File types", "order": 23, "is_completed": false },
  { "id": 24, "title": "Maps", "order": 24, "is_completed": false },
  { "id": 25, "title": "Arithmetic expressions in programming", "order": 25, "is_completed": false },
  { "id": 26, "title": "Arithmetic operations", "order": 26, "is_completed": false },
  { "id": 27, "title": "Functions", "order": 27, "is_completed": false },
  { "id": 28, "title": "Methods", "order": 28, "is_completed": false },
  { "id": 29, "title": "Interfaces", "order": 29, "is_completed": false },
  { "id": 30, "title": "Public and private scopes", "order": 30, "is_completed": false },
  { "id": 31, "title": "Working with time", "order": 31, "is_completed": false },
  { "id": 32, "title": "Anonymous functions and Closures", "order": 32, "is_completed": false },
  { "id": 33, "title": "Defer statement", "order": 33, "is_completed": false },
  { "id": 34, "title": "Variadic functions", "order": 34, "is_completed": false },
  { "id": 35, "title": "Functional decomposition", "order": 35, "is_completed": false },
  { "id": 36, "title": "Advanced Input", "order": 36, "is_completed": false },
  { "id": 37, "title": "Generating random numbers and strings", "order": 37, "is_completed": false },
  { "id": 38, "title": "Operations with maps", "order": 38, "is_completed": false },
  { "id": 39, "title": "String search", "order": 39, "is_completed": false },
  { "id": 40, "title": "Operations with strings", "order": 40, "is_completed": false },
  { "id": 41, "title": "Modules", "order": 41, "is_completed": false },
  { "id": 42, "title": "Math package", "order": 42, "is_completed": false },
  { "id": 43, "title": "File modes and permissions", "order": 43, "is_completed": false },
  { "id": 44, "title": "Working with files", "order": 44, "is_completed": false },
  { "id": 45, "title": "Reading files", "order": 45, "is_completed": false },
  { "id": 46, "title": "Writing data to files", "order": 46, "is_completed": false },
  { "id": 47, "title": "Compilers and interpreters", "order": 47, "is_completed": false },
  { "id": 48, "title": "Main (compiling and running)", "order": 48, "is_completed": false },
  { "id": 49, "title": "Command-line arguments and flags", "order": 49, "is_completed": false }
];
